[package]
name = "no_name_yet"
version = "0.1.0"
edition = "2018"

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum.git", branch = "main", default-features = false }
getopts = "0.2"
git2 = { version = "0.13", features = ["https"], default-features = false }
http = "0.2"
rust-ini = "0.17"
tempfile = "3.2"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros"] }
