[package]
name = "no_name_yet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.1", default-features = false }
git2 = { version = "0.13", default-features = false }
tokio = { version = "1.8", default-features = false, features = ["rt-multi-thread", "macros"] }
