[package]
name = "no_name_yet"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
axum = { version = "0.2", default-features = false }
getopts = "0.2"
git2 = { version = "0.13", features = ["https"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.2"
toml = "0.5"
tokio = { version = "1.11", features = ["rt-multi-thread", "macros"] }
